export const API_ENDPOINTS = {
  AUTH: {
    NONCE: '/users/get-address-nonce',
    VERIFY_SIGNATURE: 'users/verify-signature',
  },
  PRIVATE: {},
  PUBLIC: {
    GET_LAUNCHPAD: '/launchpad-homepage',
    GET_TRENDING: '/collectionla-trending-category',
    GET_TRENDING_ARTS: '/market/gettrendingart',
    GET_SPOT_LIGHT: '/collectionla-spotlight',
    GET_LAUNCHPAD_PAGE: '/launchpad-list',
    GET_LAUNCHPAD_BANNER_PAGE: '/newest',
    GET_EXPLORE_PAGE: '/collectionla',
    GET_EXPLORE_CATEGORY: '/category',
    GET_EXPLORE_BLOCKCHAIN: '/blockchain',
    GET_POPULAR_SEARCH: '/collection-popular',
    GET_COLECTION_TABLE: '/collectionla-homepage',
    GET_TRENDING_TABLE: '/collectionla-list',
    GET_COLLECTION_PAGE: '/nft-list-v3',
    GET_COLLECTION_DETAILS: '/collectionla-detail',
    GET_COLLECTION_VolumePrice: '/nft-total-volume-and-price',
    GET_COLLECTION_OWNER_DISTRIBUTION: '/nft-ownership',
    GET_COLLECTION_OWNER_TOP_50: '/nft-owner',
    GET_COLLECTION_PRICE_DISTRIBUTION: '/nft-offer-list',
  },
} as const

export const QUERIES = {
  AUTH: {
    NONCE: 'get-user-nonce',
    VERIFY_SIGNATURE: 'verify-signature',
  },
  PRIVATE: {},
  PUBLIC: {
    GET_LAUNCHPAD: '/launchpad-homepage',
    GET_TRENDING: 'market_gettrending',
    GET_TRENDING_ARTS: '/market/gettrendingart',
    GET_SPOT_LIGHT: '/collectionla-spotlight',
    GET_LAUNCHPAD_PAGE: 'launchpad_list',
    GET_EXPLORE_PAGE: 'collection',
    GET_POPULAR_SEARCH: 'collection_popular',
    GET_LAUNCHPAD_BANNER_PAGE: 'newest',
    GET_EXPLORE_CATEGORY: 'category',
    GET_EXPLORE_BLOCKCHAIN: 'blockchain',
    GET_COLECTION_TABLE: '/collectionla-homepage',
    GET_TRENDING_TABLE: '/collectionla-list',
    GET_COLLECTION_PAGE: 'nft-list-v3',
    GET_COLLECTION_DETAILS: 'collectionla-detail',
    GET_COLLECTION_VolumePrice: 'nft-total-volume-and-price',
    GET_COLLECTION_OWNER_TOP_50: 'nft-owner',
    GET_COLLECTION_OWNER_DISTRIBUTION: 'nft-ownership',
    GET_COLLECTION_PRICE_DISTRIBUTION: '/nft-offer-list',
  },
} as const
